# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SMPL Supplier' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SMPL Supplier
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'IQKeyboardManagerSwift'
pod 'lottie-ios'
 pod 'SwiftKeychainWrapper'
end
